### PR TITLE
Chat list, chat API, functionalities to chat page and bug fixes

### LINKED ISSUE #91: Chat backend
* Definir a estrutura de armazenamento interno das mensagens e chats;
* Criar chamadas necessárias para as implementações;

### PR DESCRIPTION
**Pull request by AndreLaranjeira**
## Description

* Implemented chat API;
* Implemented chat list page;
* Added some functionality and backend support for chat page;
* Some bug fixes, notably infiniteScroll now reloads data on focus;

## Motivation and Context

Closes #91 and #92.

## How has this been tested?

Tested in bits by all 3 different members.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: src/pages/Animal/Interested/index.tsx [hunk 1]
```diff
@@ -155,7 +155,6 @@ const Interested = (): JSX.Element => {
                         onPress: () => navigation.navigate('Chat', {
                           title: user.userName,
                           targetUserUID: u.id,
```
Comment (AndreLaranjeira) [inline src/pages/Animal/Interested/index.tsx:157]: A one letter variable name is a little vague... maybe rename this to `interestedUser`?

**Review by labm1997 — APPROVED** [review]
Tested and approved!

File: src/pages/Chat/Chat/index.tsx [hunk 2]
```diff
@@ -11,153 +15,110 @@ import MaterialIcons from 'react-native-vector-icons/MaterialIcons';
...
   const [messages, setMessages] = useState<IMessage[]>([]);
+  const [isLoadingEarlier, setIsLoadingEarlier] = useState<boolean>(false);
+  const [chatRef, setChatRef] = useState<DocumentRefData>();
+
+  const sorter = (a: IMessage, b: IMessage): number => (b.createdAt as Date).getTime() - (a.createdAt as Date).getTime();
+
+  const loadMessages = useCallback((lastMessage?: IMessage): void => {
+    if (!chatRef) return;
+
+    const lastTimestamp = lastMessage ? lastMessage.createdAt as Date : undefined;
```
Comment (AndreLaranjeira) [inline src/pages/Chat/Chat/index.tsx:47]: A complain on semantics, not logic: why is a variable of type Date called lastTimestamp and not lastDate or something along these lines?

File: src/pages/Chat/Chat/index.tsx [hunk 3]
```diff
@@ -11,153 +15,110 @@ import MaterialIcons from 'react-native-vector-icons/MaterialIcons';
...
+          chatAPI.markChatMessagesAsSeemByUser(chat.ref.id, currentUserRef);
+        } else {
+          setMessages([]);
+        }
+      });
+    }
+  // eslint-disable-next-line react-hooks/exhaustive-deps
   }, []);
 
+  useEffect(() => loadMessages(), [loadMessages, chatRef]);
```
Comment (AndreLaranjeira) [inline src/pages/Chat/Chat/index.tsx:102]: Question: If `loadMessages` is a callback that depends on `chatRef`, is this effect's dependency on `chatRef` really necessary?

File: src/pages/Chat/Chat/index.tsx [hunk 4]
```diff
@@ -11,153 +15,110 @@ import MaterialIcons from 'react-native-vector-icons/MaterialIcons';
...
+
+  const onSend = useCallback(async (newMessages: IMessage[] = []) => {
+    let cRef: DocumentRefData;
```
Comment (AndreLaranjeira) [inline src/pages/Chat/Chat/index.tsx:105]: Question: Do we really need cRef? Can't we just setChatRef if chatRef is undefined and then use chatRef assuming it is not undefined?

File: src/services/chat/api.ts [hunk 5]
```diff
@@ -0,0 +1,147 @@
+import firestore from '@react-native-firebase/firestore';
+import {
+  DocumentData, DocumentRefData, Query, QuerySnapshot,
+} from '../../types/firebase';
+
+// Collection de chats
```
Comment (AndreLaranjeira) [inline src/services/chat/api.ts:6]: Acho que essa referência já pode ser retirada, não?

File: src/services/chat/api.ts [hunk 6]
```diff
@@ -0,0 +1,147 @@
...
+
+const getOwnChats = (userRef: DocumentRefData)
+  : Query => firestore()
+  .collection('chats')
+  .where('users', 'array-contains', userRef);
+
+const getChatByTarget = async (currentUser: DocumentRefData, targetUser: DocumentRefData): Promise<DocumentData | undefined> => {
+  const query1 = await firestore()
+    .collection('chats')
+    .where('users', '==', [currentUser, targetUser])
```
Comment (AndreLaranjeira) [inline src/services/chat/api.ts:38]: I dislike Firebase and understand if no one wants to change this, but I wonder if `.where('users', 'in', [[currentUser, targetUser], [targetUser, currentUser]])` would work instead of 2 separate queries.

File: src/pages/Chat/Chat/index.tsx (hunk 4 above)
Comment (labm1997) [reply src/pages/Chat/Chat/index.tsx:105]: Unfortunatelly no, setChatRef is asynchronous.

File: src/pages/Chat/Chat/index.tsx (hunk 3 above)
Comment (labm1997) [reply src/pages/Chat/Chat/index.tsx:102]: Forgot that `loadMessages` is a callback depending on `chatRef`. I'll test without this `useEffect`

File: src/pages/Chat/Chat/index.tsx (hunk 4 above)
Comment (AndreLaranjeira) [reply src/pages/Chat/Chat/index.tsx:105]: Ok, but can't you use `await` in an async function?

File: src/pages/Chat/Chat/index.tsx (hunk 3 above)
Comment (labm1997) [reply src/pages/Chat/Chat/index.tsx:102]: It is required. Without it `loadMessages` is not called when the component first initialize.

File: src/pages/Chat/Chat/index.tsx (hunk 4 above)
Comment (labm1997) [reply src/pages/Chat/Chat/index.tsx:105]: setChatRef is something internal of react. It isn's an asynchronous function but it's result won't have effect immediately.

File: src/services/chat/api.ts (hunk 6 above)
Comment (labm1997) [reply src/services/chat/api.ts:24]: Let's test

Comment (labm1997) [reply src/services/chat/api.ts:24]: It works. Nice!

File: src/pages/Chat/Chat/index.tsx [hunk 7]
```diff
@@ -219,11 +180,11 @@ export default (): JSX.Element => {
           messages={messages}
           loadEarlier
           infiniteScroll
+          isLoadingEarlier={isLoadingEarlier}
```
Comment (Hugo-NF) [inline src/pages/Chat/Chat/index.tsx:183]: Probably we don't need this state anymore.

**Review by Hugo-NF — APPROVED** [review]
